import localFont from "next/font/local";
import ANavbar from '../../components/admin/ANavbar';
import "../globals.css";
// import AFooter from '../../components/admin/AFooter'

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "The Bee Blessing's | Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ANavbar>
        <main>{children}</main>
        </ANavbar>
        {/* <AFooter/> */}
      </body>
    </html>
  );
}
